-- 테이블 생성 문제

-- 1번 
DROP TABLE SCORE;
CREATE TABLE SCORE(
GRADE NUMBER(1),
ROOM NUMBER,
NAME VARCHAR2(21),
KOREAN NUMBER(3),
ENGLISH NUMBER(3),
MATH NUMBER(3)
);

INSERT INTO SCORE(GRADE, ROOM, NAME, KOREAN, ENGLISH, MATH)
VALUES(1,1,'마리오',50,60,50);
INSERT INTO SCORE(GRADE, ROOM, NAME, KOREAN, ENGLISH, MATH)
VALUES(1,1,'루이지',60,90,50);
INSERT INTO SCORE(GRADE, ROOM, NAME, KOREAN, ENGLISH, MATH)
VALUES(1,2,'쿠파',70,70,80);
INSERT INTO SCORE(GRADE, ROOM, NAME, KOREAN, ENGLISH, MATH)
VALUES(1,2,'요시',80,85,35);

SELECT * FROM SCORE;

--2번
-- 이름을 만들다보면 쓸 수 없는 단어가 있다(예약어)
-- 테이블 이름을 앞에 붙여 쓰면 문제가 사라진다.(테이블_이름)
DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT(
ACCOUNT_OWNER VARCHAR2(21),
ACCOUNT_PERIOD NUMBER,
ACCOUNT_COUNT NUMBER,
ACCOUNT_PAYMENT NUMBER,
ACCOUNT_BALANCE NUMBER
);

INSERT INTO ACCOUNT(ACCOUNT_OWNER, ACCOUNT_PERIOD, ACCOUNT_COUNT, ACCOUNT_PAYMENT, ACCOUNT_BALANCE)
VALUES('유재석',3,15,1000000,1500000);
INSERT INTO ACCOUNT(ACCOUNT_OWNER, ACCOUNT_PERIOD, ACCOUNT_COUNT, ACCOUNT_PAYMENT, ACCOUNT_BALANCE)
VALUES('강호동',2,5,500000,2500000);
INSERT INTO ACCOUNT(ACCOUNT_OWNER, ACCOUNT_PERIOD, ACCOUNT_COUNT, ACCOUNT_PAYMENT, ACCOUNT_BALANCE)
VALUES('신동엽',2,8,800000,10000000);

SELECT * FROM ACCOUNT;

