-- 테이블 생성 문제

-- 1번 
DROP TABLE SCORE;
CREATE TABLE SCORE(
GRADE NUMBER(1),
CLASS NUMBER(1),
NAME VARCHAR2(9),
KOREAN NUMBER(2),
ENGLISH NUMBER(2),
MATH NUMBER(2)
);

INSERT INTO SCORE(GRADE, CLASS, NAME, KOREAN, ENGLISH, MATH)
VALUES(1,1,'마리오',50,60,50);
INSERT INTO SCORE(GRADE, CLASS, NAME, KOREAN, ENGLISH, MATH)
VALUES(1,1,'루이지',60,90,50);
INSERT INTO SCORE(GRADE, CLASS, NAME, KOREAN, ENGLISH, MATH)
VALUES(1,2,'쿠파',70,70,80);
INSERT INTO SCORE(GRADE, CLASS, NAME, KOREAN, ENGLISH, MATH)
VALUES(1,2,'요시',80,85,35);

SELECT * FROM SCORE;

DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT(
NAME VARCHAR2(21),
YEAR NUMBER,
COUNT NUMBER,
MONTH_MONEY NUMBER,
TOTAL_MONEY NUMBER
);

INSERT INTO ACCOUNT(NAME, YEAR, COUNT, MONTH_MONEY, TOTAL_MONEY)
VALUES('유재석',3,15,1000000,1500000);
INSERT INTO ACCOUNT(NAME, YEAR, COUNT, MONTH_MONEY, TOTAL_MONEY)
VALUES('강호동',2,5,500000,250000);
INSERT INTO ACCOUNT(NAME, YEAR, COUNT, MONTH_MONEY, TOTAL_MONEY)
VALUES('신동엽',2,8,800000,10000000);

SELECT * FROM ACCOUNT;

